services:
  minio:
    image: quay.io/minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    container_name: redis-stack
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  app:
    build: 
      context: ./app
    depends_on:
      - minio
      - redis
      - rabbitmq
    ports:
      - "5000:5000"


  nginx:
    build:
      context: ./nginx
    depends_on:
      - app
    ports:
      - "8080:80"

volumes:
  minio_data:
  redis_data:
  rabbitmq_data: